name: Build and Publish VS Code Extension

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Configure Git
        run: |
          git config --local user.email "m@b.c"
          git config --local user.name "b"

      - name: Install Dependencies
        run: npm install

      # - name: Package Extension
      #   run: npm run vscode:prepublish

      - name: Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx @vscode/vsce publish
